sudo tee /var/ossec/etc/ossec.conf <<EOF
<ossec_config>
<global>
<jsonout_output>yes</jsonout_output>
<alerts_log>yes</alerts_log>
<logall>yes</logall>
<logall_json>yes</logall_json>
</global>

<remote>
<connection>secure</connection>
<port>1514</port>
<protocol>tcp</protocol>
</remote>

<wodle name="aws-s3">
<disabled>no</disabled>
<interval>10m</interval>
<run_on_start>yes</run_on_start>
<skip_on_error>yes</skip_on_error>
<bucket type="waf">
<name>aws-waf-logs-maroon</name>
<only_logs_after>2026-MAR-20</only_logs_after>
</bucket>
<bucket type="custom">
<name>maroon-cloudfront-logs</name>
<only_logs_after>2026-MAR-20</only_logs_after>
</bucket>
<bucket type="custom">
<name>maroon-central-network-firewall-logs</name>
<only_logs_after>2026-MAR-20</only_logs_after>
</bucket>
<bucket type="custom">
<name>maroon-cognito-user-pool-logs-156041414531-us-east-2-an</name>
<only_logs_after>2026-MAR-20</only_logs_after>
</bucket>
</wodle>
</ossec_config>
EOF